[package]
name    = "api-convert"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = false
strip = true
codegen-units = 1
opt-level = "z"
lto = true
panic = "abort"

[dependencies]
api-shared   = { path = "../api-shared" }
parser       = { path = "../parser" }
service      = { path = "../service" }
lambda_http  = "1.2"
serde        = { version = "1", features = ["derive"] }
serde_json   = "1"
tokio        = { version = "1", features = ["full"] }
