[[mcp_servers]]
name = "boldify-mcp-local"
transport = "http"
url = "http://localhost:3000/mcp"

[[mcp_servers]]
name = "boldify-mcp-prod"
transport = "http"
url = "https://tzzmabgke46hc4xpfntkgc4tru0rlggf.lambda-url.eu-west-1.on.aws/mcp"
disabled = false

[tools.bash]
allowlist = [
    "find",
    "grep *",
]
