[[mcp_servers]]
name = "boldify-mcp-local"
transport = "http"
command = "http://localhost:3000/mcp"

[[mcp_servers]]
name = "boldify-mcp-prod"
transport = "http"
url = "https://api.boldify.net/mcp"
disabled = false

[tools.bash]
allowlist = [
    "grep *",
]
