[package]
name    = "mcp"
version = "0.1.0"
edition = "2021"

[features]
default = []
cli     = ["rmcp/transport-io"]
http    = ["rmcp/transport-sse-server", "tokio/full", "dep:axum"]

[dependencies]
service    = { path = "../service" }
rmcp       = { version = "0.10" }
serde_json = "1"
tokio      = { version = "1", optional = true }
axum       = { version = "0.7", optional = true }
