[package]
name    = "mcp"
version.workspace = true
edition = "2021"

[features]
default = []
cli     = ["rmcp/transport-io", "tokio/io-std", "tokio/rt-multi-thread"]
http    = ["rmcp/transport-streamable-http-server", "tokio/net", "tokio/signal", "tokio/rt-multi-thread", "tokio/macros", "dep:axum"]

[dependencies]
service    = { path = "../service" }
rmcp       = { version = "2.2" }
serde      = { version = "1", features = ["derive"] }
serde_json = "1"
tokio      = { version = "1", features = ["rt", "macros"] }
axum                = { version = "0.8", optional = true }
tracing             = "0.1"
tracing-subscriber  = { version = "0.3", features = ["env-filter"] }
